---
#
#-----------------------------------------------------------------------------
# Tasks file.:  step-05_promote_ccv.yaml
#
# Author.....:  Andy Thom
#
# Date.......:  02/12/2019
#
#
# Description:
#-----------------------------------------------------------------------------
#
# These tasks will:-
#
# Promote CCV's up-to a specific lifecycle
#
#
# i.e.  If the Lifecycle Environment Path consists of the following:-
#
#         pilot -> low -> average -> high -> critical
#
#
#       and we request to promote: 'average' then the tasks will promote to 
#       *ALL* the environments: "pilot", "low" and also "average".
#
#
# To use this task collection put the following in the 
# 'tasks:' section of the playbook:-
#
#   - include: step-05_promote_ccv.yaml
#
#-----------------------------------------------------------------------------
#
#
- set_fact:
    _task_name_prefix: "STEP 05  -  COMPOSITE CONTENT VIEW"


#
#----
# Define the task type.
#
# This is used in sub-task: _promote_content.yaml to record the task in
# dictionary:-
#
#   _task_info
#
#
- name: "{{ _task_name_prefix }}  -  SET TASK TYPE"
  set_fact:
    _task_type: "PROMOTE CCV"


#
#----
# PROMOTE CCV's to a lifecycle
#
# Requires the parameter: 'satcb_promote_ccv_to_env' to be defined.
#
# If: 'satcb_promote_ccv_only' is FALSE but: 'satcb_promote_ccv_to_env'
# then new CV/CCV versions will be published *before* being promoted.
#
#
# NOTE #1:  Promotion is *ONLY* done if:-
#
#           a)  satcb_promote_ccv_only is TRUE
#
#               and,
#
#
#           b)  satcb_promote_ccv_to_env is defined
#
#               or,
#
#
#           c)  satcb_force_promotion is TRUE (default: false)
#
#               or,
#
#
#           d)  The content has *NOT* already been promoted to
#               the Lifecycle. 
#
#
# NOTE #2:  We do *not* remove old CCV's - yet. This
#           will be done *AFTER* the promotion stage.
#
#
- block:
  - name: "{{ _task_name_prefix }}  -  PROMOTE THE CCVs"
    include_tasks:
      _promote_content.yaml
    loop: "{{ _publish_ccv_list }}"
    loop_control:
      loop_var: _content_name
    when:
      - _publish_ccv_list is defined
      - _publish_ccv_list|length > 0
      - satcb_promote_ccv_only  | bool == true or satcb_promote_ccv_to_env is defined
      - satcb_promote_ccv_to_env | length > 0
    register: _sat_promote_ccv_result
  rescue:
    - set_fact:
        _PLAYBOOK_STATUS: "ERROR"
        _PLAYBOOK_ERROR_MSG: "{{ _PLAYBOOK_ERROR_MSG + [ '{{ _task_name_prefix }} - There was a error promoting CCV: {{ _content_name }}' ] }}"
      changed_when: true
      failed_when: false
      notify: mail_report
  when: _PLAYBOOK_STATUS == "SUCCESS"
  tags:
    - promote_ccv


- debug:
    var: _sat_promote_ccv_result
  when: _DEBUG_ME == true
