---
#
#-----------------------------------------------------------------------------
# Tasks file.:  step-04_publish_ccv.yaml
#
# Author.....:  Andy Thom
#
# Date.......:  02/12/2019
#
#
# Description:
#-----------------------------------------------------------------------------
#
# These tasks will:-
#
# a) determine which CCV's should be PUBLISHED
#
# b) Publish the CCV's to new versions.
#
#
# To use this task collection put the following in the 
# 'tasks:' section of the playbook:-
#
#   - include: step-04_publish_ccv.yaml
#
#-----------------------------------------------------------------------------
#
#
- set_fact:
    _task_name_prefix: "STEP 04  -  COMPOSITE CONTENT VIEW PUBLISH"



#
#---
# Prepare some list variables
#
#
- set_fact:
    _temp_list: []
    _temp_include_list: []
    _publish_ccv_list: []


#
#----
# NOW PUBLISH THE COMPOSITE CONTENT VIEWS
#
#
- name: "{{ _task_name_prefix }}  -  ADD CCVs TO TEMPORARY LIST"
  set_fact:
    _temp_list: "{{ _temp_list + [item.key]}}"
  with_dict: "{{ _ccv_cv_list }}"


- name: "{{ _task_name_prefix }}  -  REMOVE DUPLICATE ENTRIES FROM CCV LIST"
  set_fact:
    _temp_list: "{{ _temp_list | unique }}"


##
- block:
  - name: "{{ _task_name_prefix }}  -  INCLUDE CCVs TO FROM INCLUDE LIST"
    set_fact:
      _temp_include_list: "{{ _temp_include_list + [item] if item in satcb_include_list else _temp_include_list }}"
    with_list: "{{ _temp_list }}"


  - debug:
      var: _temp_include_list

  #
  #----
  # Once we get our list of CV's to be included we need to make sure this is
  # put back to into the temporary list so the 'exclude' list can be worked
  # on.
  #
  #
  - set_fact:
      _temp_list: "{{ _temp_include_list | list }}"

  when: (satcb_include_list is defined) and (satcb_include_list | length > 0)
##


- name: "{{ _task_name_prefix }}  -  REMOVE CCVs TO BE EXCLUDED"
  set_fact:
    _publish_ccv_list: "{{ _publish_ccv_list + [item] if item not in satcb_exclude_list else _publish_ccv_list }}"
  with_list: "{{ _temp_list }}"
  when: satcb_exclude_list is defined


- debug:
    var: _temp_list
  when: _DEBUG_ME == true

- debug:
    var: _publish_ccv_list


#
#----
# Define the task type.
#
# This is used in sub-task: _publish_content.yaml to record the task in
# dictionary:-
#
#   _task_info
#
#
- name: "{{ _task_name_prefix }}  -  SET TASK TYPE"
  set_fact:
    _task_type: "PUBLISH CCV"


#
#----
# PUBLISH new versions all the CCV's in the list: _publish_ccv_list
#
# NOTE: We do *not* remove old CCV's - yet. This will be done
#       AFTER the promotion stage.
#
#
- block:
  - name: "{{ _task_name_prefix }}  -  PUBLISH THE CCVs ..."
    include_tasks:
      _publish_content.yaml
    loop: "{{ _publish_ccv_list }}"
    loop_control:
      loop_var: _content_name
    when:
      - _publish_ccv_list is defined
      - _publish_ccv_list|length > 0
      - satcb_promote_ccv_only  | bool == false
    register: _sat_publish_ccv_result
  rescue:
    - set_fact:
        _PLAYBOOK_STATUS: "ERROR"
        _PLAYBOOK_ERROR_MSG: "{{ _PLAYBOOK_ERROR_MSG + [ '{{ _task_name_prefix }}  -  There was a error publishing new version of CCV: {{ sat_cv_name }}' ] }}"
      changed_when: true
      failed_when: false
      notify: mail_report
  when: _PLAYBOOK_STATUS == "SUCCESS"
  tags:
    - publish_ccv

- debug:
    var: _sat_publish_ccv_result
  when: _DEBUG_ME == true


- debug:
    var: _task_info
